# Generated by Django 4.0.3 on 2022-03-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('a_paterno', models.CharField(max_length=60)),
                ('a_Materno', models.CharField(max_length=60)),
                ('edad', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('No Binario', 'No Binario')], default=1, max_length=60)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
    ]
