# Generated by Django 4.0.3 on 2022-03-22 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_alter_usuario_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nombres',
        ),
    ]
