# Generated by Django 4.0.3 on 2022-03-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_usuario_nombres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario_administrador',
            field=models.BooleanField(default=True),
        ),
    ]
