# Generated by Django 4.0.3 on 2022-03-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_alter_usuario_usuario_administrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario_administrador',
            field=models.BooleanField(default=False),
        ),
    ]
